
CREATE TABLE IF NOT EXISTS TABLATEMPORAL
(
NOMBRE_VICTIMA varchar(50),
APELLIDO_VICTIMA varchar(50),
DIRECCION_VICITMA varchar(80),
FECHA_PRIMERA_SOSPECHA datetime,
FECHA_CONFIRMACION datetime,
FECHA_MUERTE datetime,
ESTADO_VICTIMA varchar(30),
NOMBRE_ASOCIADO varchar(50),
APELLIDO_ASOCIADO varchar(50),
FECHA_CONOCIO datetime,
CONTACTO_FISICO varchar(30),
FECHA_INICIO_CONTACTO datetime,
FECHA_FIN_CONTACTO datetime,
NOMBRE_HOSPITAL varchar(50),
DIRECCION_HOSPITAL varchar(80),
UBICACION_VICTIMA varchar(80),
FECHA_LLEGADA datetime,
FECHA_RETIRO datetime,
TRATAMIENTO varchar(50),
EFECTIVIDAD int,
FECHA_INICIO_TRATAMIENTO datetime,
FECHA_FIN_TRATAMIENTO datetime,
EFECTIVIDAD_EN_VICTIMA int
);

LOAD DATA LOCAL INFILE '/home/jacky/Documentos/[MIA]PRACTICA1/GRAND_VIRUS_EPICENTER.csv'
INTO TABLE TABLATEMPORAL
FIELDS terminated by ';'
ENCLOSED BY ''
ESCAPED BY ''
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM TABLATEMPORAL;

INSERT IGNORE INTO VICTIMA(NOMBRE, APELLIDO, DIRECCION)
SELECT DISTINCT NOMBRE_VICTIMA, APELLIDO_VICTIMA, DIRECCION_VICITMA FROM TABLATEMPORAL
WHERE NOMBRE_VICTIMA!="";

SELECT * FROM VICTIMA;

INSERT IGNORE INTO HOSPITAL(NOMBRE, DIRECCION)
SELECT DISTINCT NOMBRE_HOSPITAL, DIRECCION_HOSPITAL FROM TABLATEMPORAL
WHERE NOMBRE_HOSPITAL!="";

SELECT * FROM HOSPITAL;

INSERT IGNORE INTO TRATAMIENTO(NOMBRE, EFECTIVIDAD)
SELECT DISTINCT TRATAMIENTO, EFECTIVIDAD FROM TABLATEMPORAL
WHERE TRATAMIENTO!="";

SELECT * FROM TRATAMIENTO;

INSERT IGNORE INTO ASOCIADO(NOMBRE, APELLIDO, FECHACONOCIMIENTO)
SELECT DISTINCT NOMBRE_ASOCIADO, APELLIDO_ASOCIADO, FECHA_CONOCIO FROM TABLATEMPORAL
WHERE NOMBRE_ASOCIADO!="";



SELECT * FROM ASOCIADO;

INSERT IGNORE INTO LUGAR(UBICACION)
SELECT DISTINCT UBICACION_VICTIMA FROM TABLATEMPORAL
WHERE UBICACION_VICTIMA!="";

SELECT * FROM LUGAR;

INSERT IGNORE INTO TIPOCONTACTO(CONTACTO)
SELECT DISTINCT CONTACTO_FISICO FROM TABLATEMPORAL
WHERE CONTACTO_FISICO!="";

SELECT * FROM TIPOCONTACTO;

INSERT IGNORE INTO STATUSENFERMEDAD(ESTADO)
SELECT DISTINCT ESTADO_VICTIMA FROM TABLATEMPORAL
WHERE ESTADO_VICTIMA!='';

SELECT * FROM STATUSENFERMEDAD;

INSERT IGNORE INTO CONTROLTRATAMIENTO(ID_VICTIMA,ID_TRATAMIENTO,EFECTIVIDADVICTIMA, FECHAFIN, FECHAINICIO)
SELECT DISTINCT VIC.ID_VICTIMA, TRA.ID_TRATAMIENTO, TT.EFECTIVIDAD_EN_VICTIMA,TT.FECHA_FIN_TRATAMIENTO, TT.FECHA_INICIO_TRATAMIENTO
FROM TRATAMIENTO AS TRA, VICTIMA AS VIC, TABLATEMPORAL AS TT
WHERE TRA.NOMBRE=TT.TRATAMIENTO AND VIC.NOMBRE=TT.NOMBRE_VICTIMA AND VIC.APELLIDO=TT.APELLIDO_VICTIMA AND TRA.EFECTIVIDAD=TT.EFECTIVIDAD_EN_VICTIMA;

SELECT * FROM CONTROLTRATAMIENTO;

INSERT IGNORE INTO CONTROL_LUGAR(ID_LUGAR, ID_VICTIMA, FECHAHORALLEGADA, FECHAHORASALIDA)
SELECT DISTINCT LU.ID_LUGAR, VIC.ID_VICTIMA, TT.FECHA_LLEGADA, TT.FECHA_RETIRO
FROM LUGAR AS LU, VICTIMA AS VIC, TABLATEMPORAL AS TT
WHERE LU.UBICACION=TT.UBICACION_VICTIMA AND VIC.NOMBRE=TT.NOMBRE_VICTIMA AND VIC.APELLIDO=TT.APELLIDO_VICTIMA;

SELECT * FROM CONTROL_LUGAR;

INSERT IGNORE INTO VICTIMA_ASOCIADO(ID_ASOCIADO,ID_VICTIMA,ID_TIPOCONTACTO, FECHAINICIO, FECHAFIN)
SELECT DISTINCT ASOC.ID_ASOCIADO, VIC.ID_VICTIMA, TC.ID_TIPOCONTACTO, TT.FECHA_INICIO_CONTACTO, TT.FECHA_FIN_CONTACTO
FROM ASOCIADO AS ASOC, VICTIMA AS VIC, TIPOCONTACTO AS TC, TABLATEMPORAL AS TT
WHERE ASOC.NOMBRE=TT.NOMBRE_ASOCIADO AND ASOC.APELLIDO=TT.APELLIDO_VICTIMA AND VIC.NOMBRE=TT.NOMBRE_VICTIMA AND VIC.APELLIDO=TT.APELLIDO_VICTIMA AND TC.CONTACTO=TT.CONTACTO_FISICO;

SELECT * FROM VICTIMA_ASOCIADO;

INSERT IGNORE INTO REGISTRO_VICTIMA(ID_VICTIMA,ID_HOSPITAL, ID_STATUS, FECHASOSPECHOSA, FECHACONFIRMACION, FECHAMUERTE)
SELECT DISTINCT VIC.ID_VICTIMA, HOS.ID_HOSPITAL, STA.ID_STATUS, TT.FECHA_PRIMERA_SOSPECHA, TT.FECHA_CONFIRMACION, TT.FECHA_MUERTE
FROM VICTIMA AS VIC, HOSPITAL AS HOS, STATUSENFERMEDAD AS STA, TABLATEMPORAL AS TT
WHERE HOS.NOMBRE=TT.NOMBRE_HOSPITAL AND VIC.NOMBRE=TT.NOMBRE_VICTIMA AND VIC.APELLIDO=TT.APELLIDO_VICTIMA;

SELECT * FROM REGISTRO_VICTIMA;