/*-------------------CONSULTA 1--------------------------*/
SELECT count(*)
FROM REGISTRO_VICTIMA
WHERE FECHAMUERTE!=0 AND ID_HOSPITAL=4;

/*--------------------------------------------------------------------*/
SELECT HOSPITAL.NOMBRE, HOSPITAL.DIRECCION, count(REGISTRO_VICTIMA.FECHAMUERTE) AS CANTIDAD_MUERTES
FROM HOSPITAL
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_HOSPITAL=HOSPITAL.ID_HOSPITAL
WHERE REGISTRO_VICTIMA.FECHAMUERTE!=0
group by HOSPITAL.NOMBRE, HOSPITAL.DIRECCION;
/*--------------------------------------------------------------------*/

/*-------------------CONSULTA 2--------------------------*/

	SELECT * FROM TRATAMIENTO;
    SELECT * FROM CONTROLTRATAMIENTO;
    SELECT * FROM REGISTRO_VICTIMA;
    
/*--------------------------------------------------------------------*/
	SELECT VICTIMA.NOMBRE, VICTIMA.APELLIDO
	FROM VICTIMA 
    INNER JOIN REGISTRO_VICTIMA
    ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
	INNER JOIN CONTROLTRATAMIENTO
    ON CONTROLTRATAMIENTO.ID_VICTIMA=VICTIMA.ID_VICTIMA
    WHERE REGISTRO_VICTIMA.ID_STATUS=2 AND CONTROLTRATAMIENTO.ID_TRATAMIENTO=2 AND  CONTROLTRATAMIENTO.EFECTIVIDADVICTIMA>5
    ORDER BY VICTIMA.NOMBRE ASC;
/*--------------------------------------------------------------------*/    

/*-------------------CONSULTA 3--------------------------*/
SELECT * FROM STATUSENFERMEDAD;
	
/*--------------------------------------------------------------------*/
SELECT VICTIMA.NOMBRE, VICTIMA.APELLIDO, VICTIMA.DIRECCION, COUNT(VICTIMA_ASOCIADO.ID_ASOCIADO) AS NUMEROASOC
FROM VICTIMA
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN VICTIMA_ASOCIADO
ON VICTIMA_ASOCIADO.ID_VICTIMA=VICTIMA.ID_VICTIMA
WHERE REGISTRO_VICTIMA.FECHAMUERTE IS NOT NULL
group by VICTIMA.NOMBRE, VICTIMA.APELLIDO, VICTIMA.DIRECCION
having NUMEROASOC>3;


/*--------------------------------------------------------------------*/

/*-------------------CONSULTA 4--------------------------*/
SELECT * FROM TIPOCONTACTO;

SELECT VICTIMA.NOMBRE, VICTIMA.APELLIDO, COUNT(VICTIMA_ASOCIADO.ID_ASOCIADO) AS NUMEROASOC, VICTIMA_ASOCIADO.ID_TIPOCONTACTO
FROM VICTIMA
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN VICTIMA_ASOCIADO
ON VICTIMA_ASOCIADO.ID_VICTIMA=VICTIMA.ID_VICTIMA
WHERE REGISTRO_VICTIMA.ID_STATUS=5 AND VICTIMA_ASOCIADO.ID_TIPOCONTACTO=6
GROUP BY VICTIMA.NOMBRE, VICTIMA.APELLIDO, VICTIMA_ASOCIADO.ID_TIPOCONTACTO
HAVING NUMEROASOC>=2;


/*-------------------CONSULTA 5--------------------------*/
SELECT * FROM TRATAMIENTO;

SELECT VICTIMA.NOMBRE, VICTIMA.APELLIDO
FROM VICTIMA
INNER JOIN CONTROLTRATAMIENTO
ON CONTROLTRATAMIENTO.ID_VICTIMA=VICTIMA.ID_VICTIMA
WHERE CONTROLTRATAMIENTO.ID_TRATAMIENTO=3
GROUP BY VICTIMA.NOMBRE,VICTIMA.APELLIDO,VICTIMA.ID_VICTIMA
ORDER BY  COUNT(CONTROLTRATAMIENTO.ID_TRATAMIENTO) LIMIT 5;

/*-------------------CONSULTA 6--------------------------*/
SELECT VICTIMA.NOMBRE, VICTIMA.APELLIDO, REGISTRO_VICTIMA.FECHAMUERTE
FROM VICTIMA
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN CONTROLTRATAMIENTO
ON CONTROLTRATAMIENTO.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN CONTROL_LUGAR
ON CONTROL_LUGAR.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN LUGAR 
ON LUGAR.ID_LUGAR=CONTROL_LUGAR.ID_LUGAR
WHERE LUGAR.UBICACION="1987 Delphine Well" AND CONTROLTRATAMIENTO.ID_TRATAMIENTO=1;


/*-------------------CONSULTA 7--------------------------*/
SELECT DISTINCT VICTIMA.NOMBRE, VICTIMA.APELLIDO, VICTIMA.DIRECCION, COUNT(CONTROLTRATAMIENTO.ID_TRATAMIENTO)=2 AS TRATAMIENTO, COUNT(VICTIMA_ASOCIADO.ID_ASOCIADO) AS ASOCIADOS
FROM VICTIMA
INNER JOIN VICTIMA_ASOCIADO
ON VICTIMA_ASOCIADO.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN CONTROLTRATAMIENTO
ON CONTROLTRATAMIENTO.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN HOSPITAL
ON REGISTRO_VICTIMA.ID_HOSPITAL=HOSPITAL.ID_HOSPITAL
WHERE (SELECT DISTINCT COUNT(VICTIMA_ASOCIADO.ID_ASOCIADO) FROM VICTIMA_ASOCIADO WHERE VICTIMA_ASOCIADO.ID_VICTIMA=VICTIMA.ID_VICTIMA)<2
GROUP BY VICTIMA.NOMBRE, VICTIMA.APELLIDO, VICTIMA.DIRECCION
HAVING  COUNT(CONTROLTRATAMIENTO.ID_TRATAMIENTO)=2 ;

/*-------------------CONSULTA 8--------------------------*/
(SELECT month(REGISTRO_VICTIMA.FECHASOSPECHOSA) AS MES, VICTIMA.NOMBRE, VICTIMA.APELLIDO, COUNT(CONTROLTRATAMIENTO.ID_TRATAMIENTO) AS TRATA
FROM VICTIMA
INNER JOIN CONTROLTRATAMIENTO
ON CONTROLTRATAMIENTO.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
GROUP BY VICTIMA.NOMBRE, MES, VICTIMA.APELLIDO
 ORDER BY TRATA DESC LIMIT 10)
UNION 
(SELECT month(REGISTRO_VICTIMA.FECHASOSPECHOSA) AS MES, VICTIMA.NOMBRE, VICTIMA.APELLIDO, COUNT(CONTROLTRATAMIENTO.ID_TRATAMIENTO) AS TRATA
FROM VICTIMA
INNER JOIN CONTROLTRATAMIENTO
ON CONTROLTRATAMIENTO.ID_VICTIMA=VICTIMA.ID_VICTIMA
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
GROUP BY VICTIMA.NOMBRE, MES, VICTIMA.APELLIDO
 ORDER BY TRATA ASC LIMIT 10);



/*-------------------CONSULTA 9--------------------------*/
SELECT HOSPITAL.NOMBRE,((SELECT COUNT(HOSPITAL.ID_HOSPITAL))*100/(SELECT count(REGISTRO_VICTIMA.ID_VICTIMA) FROM REGISTRO_VICTIMA)) AS NUMERADOR
FROM HOSPITAL
INNER JOIN REGISTRO_VICTIMA
ON REGISTRO_VICTIMA.ID_HOSPITAL=HOSPITAL.ID_HOSPITAL
group by HOSPITAL.NOMBRE;

/*-------------------CONSULTA 10--------------------------*/
	SELECT HOSPITAL.NOMBRE, TIPOCONTACTO.CONTACTO, 
    (
    ((COUNT(TIPOCONTACTO.ID_TIPOCONTACTO))*100)/(SELECT COUNT(VICTIMA_ASOCIADO.ID_TIPOCONTACTO) FROM VICTIMA_ASOCIADO)
    ) AS PORCENTAJE
	FROM VICTIMA_ASOCIADO
	INNER JOIN TIPOCONTACTO
	ON VICTIMA_ASOCIADO.ID_TIPOCONTACTO=TIPOCONTACTO.ID_TIPOCONTACTO
	INNER JOIN VICTIMA
	ON VICTIMA_ASOCIADO.ID_VICTIMA=VICTIMA.ID_VICTIMA
	INNER JOIN REGISTRO_VICTIMA
	ON REGISTRO_VICTIMA.ID_VICTIMA=VICTIMA.ID_VICTIMA
	INNER JOIN HOSPITAL
	ON REGISTRO_VICTIMA.ID_HOSPITAL=HOSPITAL.ID_HOSPITAL
	GROUP BY HOSPITAL.NOMBRE, TIPOCONTACTO.CONTACTO
    ORDER BY HOSPITAL.ID_HOSPITAL;
